spring:
  application:
    name: Deployzilla
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:admin}
      timeout: 60000
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27021}
      database: ${SPRING_DATA_MONGODB_DATABASE:deployzilla}
server:
  port: 8081
