spring:
  application:
    name: Deployzilla
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:admin}
      timeout: 60000
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/deployzilla}
      database: ${SPRING_DATA_MONGODB_DATABASE:deployzilla}
server:
  port: 8081

sonar:
  web:
    username: admin
    password: admin
  url: http://sonar:9000