spring:
  application:
    name: Deployzilla
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:admin}
      timeout: 60000
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/deployzilla}
      database: ${SPRING_DATA_MONGODB_DATABASE:deployzilla}
server:
  port: 8081

sonar:
  web:
    username: ${SONAR_USERNAME:admin}
    password: ${SONAR_PASSWORD}
  url: ${SONAR_URL:http://sonarqube:9000}

deployzilla:
  workspace:
    path: /tmp/deployzilla
  remote:
    enabled: false              # Set to false to run locally
    host: "147.79.114.156"       # IP of the remote worker machine
    user: ${DEPLOYZILLA_REMOTE_USER:root}               # User on the remote machine (must have docker access)
    password: ${DEPLOYZILLA_REMOTE_PASSWORD:}
    port: ${DEPLOYZILLA_REMOTE_PORT:22}

  # 2. Private Registry Credentials (for Pulling)
  docker:
    registry:
      username: "${DOCKER_REGISTRY_USER:}"      # Inject via Env Var
      password: "${DOCKER_REGISTRY_PASSWORD:}"  # Inject via Env Var
      url: "https://index.docker.io/v1/"       # Default for Docker Hub
